kramdown:
  input: GFM

gems:
  - jekyll-sitemap


fairfieldinn:
    results:
        - Did Grandma just friend you? Now over half of all Americans have a profile on a social networking site.
        - Staying in touch or a waste of time? 25% of Americans hit social networking sites multiple times per day.
        - Much ado about to-dos – more than 70% of successful business owners say a to-do list is the one organizational must to keep all of their the plates spinning.
        - Boldly go! - 67% of business travelers are visiting new destinations.
        - File your expense reports! Sales trips account for 21% of all domestic business travel.
        - Bring your Rubik's Cube - Generation X (those born between 1965 and 1980) makes up 36% of all business travelers.
